# Generated by Django 3.2.6 on 2021-08-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(default='Welcome to my  Home Page', max_length=100),
        ),
    ]
